#ifndef lint
  static char SccsId[] = "@(#)stone.c    V1.1    3/28/91";
#endif

/* stone.c
   Version 1.2 (February 28, 2022)
   
   Based on The Last Stone Game
   Applesoft Version 1.1 Written on January 2, 1985
   C Version 1.2 Written on February 8, 1991
*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

typedef char bool;

#define YES 1
#define NO  0
#define MAXNUMPILES 10
#define WIN   1
#define LOSE -1
#define CONT  0

char y;
static int a, rr, n, i, j, sm, av, ch, n1, n2, n3, pm, am, col, stn;
static int f, k, l, temp, d2, d3, dm, da;
static int A[MAXNUMPILES], P[MAXNUMPILES], P1[MAXNUMPILES], P2[MAXNUMPILES];
static int B[MAXNUMPILES], F[MAXNUMPILES];
static int status;

/* stone3.c fundecl */
/* Generated by generate on Mon Mar 25 14:17:36 EST 1991  */
/* generate Written by DD */
void nim_computer();
static void declare();
static bool dgen();
static void four();
void nim_human();
static bool one();
static void random_choice();
static float randy();
void nim_setup();
static void three();
static void three_special();
static void two();

char *usage = "%s: <whostarts> <numpiles> <numstones1> [<numstones2> ... <numstones9>]";

/* Main Program */
int main( argc, argv )
int argc;
char **argv;
{
  int numstones[MAXNUMPILES];
  int numpiles, pile, stones;
  
  status = CONT;  
  if( argc < 4 )
  {
    printf( usage, argv[0] );
    exit(1);
  }

  sscanf( argv[2], "%d", &numpiles );
  for( i=1; i<=numpiles; i++ )
    sscanf( argv[i+2], "%d", &numstones[i] );
  
  nim_setup( argv[1][0], numpiles, numstones );
  
  if( y == 'y' )
  {    
    nim_computer( &pile, &stones );
    printf( "I will remove %d stone(s) from pile %d.\n", stones, pile );
    for( i=1; i<=n; i++ )
    {    
      for( j=1; j<=A[i]; j++ )
	printf( "*" );
      printf( "\n" );
    }
  }
  
  do
  {
    do 
    {    
      printf( "Which pile? " );
      scanf( "%d", &i );
      printf( "Stones to remove? " );
      scanf( "%d", &a );
    }
    while( (i<0 || i>9) || (a<0 || a>9) || (a > A[i]) );
    nim_human( i, a );
    nim_computer( &pile, &stones );    
    printf( "I will remove %d stone(s) from pile %d.\n", stones, pile );
    for( i=1; i<=n; i++ )
    {    
      for( j=1; j<=A[i]; j++ )
	printf( "*" );
      printf( "\n" );
    }
  }
  while( rr != 0 );
  if( status == WIN )
    printf( "Congratulations! You win. \n" );
  else
    printf( "Sorry! You lose.\n" );  
}

/* Setup */
void nim_setup( whostarts, numpiles, numstones )
char whostarts;
int numpiles;
int numstones[10];
{
  n = numpiles;  

  for( i=1; i<=n; i++ )
    A[i] = numstones[i];  

  for( i=1; i<=n; i++ )
  {    
    for( j=1; j<=A[i]; j++ )
      printf( "*" );
    printf( "\n" );
  }

  y = whostarts;
}

/* Computer plays */
void nim_computer( pile, stones )
int *pile, *stones;
{
  rr = 0;
  sm = 0;
  for( i=1; i<=n; i++ )
  {
    if( A[i] > 0 )
    {
      rr++;
      P[rr] = i;
      sm += A[i];
    }
  }
  if( rr >= 3 )
    dgen();
  if( rr > 4 )
  {
    av = sm/rr;
    random_choice();
    declare();
    *pile = col;
    *stones = stn;    
    return;
  }
  if( rr == 4 )
    four();
  if( rr == 4 && (ch == 2 || ch == 3) )
  {    
    declare();
    *pile = col;
    *stones = stn;    
    return;
  }
  if( rr == 4 && ch != 3 )
  {
    if( dgen() == YES )
    {
      *pile = col;
      *stones = stn;          
      return;    
    }    
    random_choice();
    declare();
    *pile = col;
    *stones = stn;    
    return;
  }
  if( rr == 3 )
  {
    three();
    declare();
    *pile = col;
    *stones = stn;    
    return;
  }
  if( rr == 2 )
  {
    two();
    declare();
    *pile = col;
    *stones = stn;    
    return;
  }
  if( rr == 1 )
  {
    if( one() == YES )
    {
      *pile = col;
      *stones = stn;          
      return;    
    }    
    declare();
    *pile = col;
    *stones = stn;    
    return;
  }
  status = LOSE;  
  *pile = col;
  *stones = stn;    
  return;
}

/* Accept human play */
void nim_human( pile, stones )
int pile, stones;
{
  A[pile] -=  stones;
}

/* Degenerate cases */
static bool dgen()
{
  char *s = "DGEN";
  bool pop = NO;
  
  n1 = n2 = n3 = f = 0;
  for( i=1; i<=rr; i++ )
  {
    if( A[P[i]] > 2 && f == 1 )
      return pop;
    if( A[P[i]] > 2 )
    {
      f = 1;
      n3++;
      P2[n3 + n2] = P[i];      
    }
    if( A[P[i]] == 1 )
    {
      n1++;
      P1[n1] = P[i];
    }
    if( A[P[i]] == 2 )
    {
      n2++;
      P2[n2] = P[i];
    }
  }
  if( n1 == 1 && n2 == 1 )
    return pop;
  n2 += n3;
  pm = am = 0;
  for( i=1; i<=n2; i++ )
  {
    if( A[P2[i]] > am )
    {
      pm = P2[i];
      am = A[P2[i]];
    }
  }   
  if( n2 == 2 && am == 2 && n1/2 != (float)n1/2 )
  {
    col = P1[(int)(randy(1) * n1 + 1)];
    stn = 1;
    declare();
    pop = YES;
    return pop;
  }
  if( n2/2 == (float)n2/2 )
    return pop;
  if( n2 == 1 )
  {    
    if( rr/2 == (float)rr/2 )
    {
      stn = A[pm];
      col = pm;
      declare();
      pop = YES;      
      return pop;
    }
    else
    {
      stn = A[pm] - 1;
      col = pm;
      declare();
      pop = YES;      
      return pop;
    }
  }
  if( n2 == 0 )
    return pop;
  
  if( n1 != 0 && n2/2 != (float)n2/2 )
  {
    col = pm;
    stn = A[col] - 1;
    declare();
    pop = YES;    
    return pop;
  }
  if( n1 != 0 && n2/2 == (float)n2/2 )
  {
    col = pm;
    stn = A[col]-2;
    declare();
    pop = YES;
    return pop;
  }
  return pop;  
}

/* One remaining pile */
static bool one()
{  
  char *s = "1 Pile";
  bool pop = NO;
  
  col = P[1];
  if( A[P[1]] > 1 )
  {    
    stn = A[P[1]] - 1;
    return pop;
  }
  stn = 1;
  declare();
  status = WIN;
  rr = 0;
  pop = YES;
  return pop;  
}

/* Two remaining piles */
static void two()
{
  char *s = "2 Piles";
  if( A[P[1]] == 1 )
  {
    stn = A[P[2]];
    col = P[2];
    return;
  }
  if( A[P[2]] == 1 )
  {
    stn = A[P[2]];
    col = P[2];
    return;
  }
  if( A[P[1]] == A[P[2]] )
  {
    stn = 1;
    col = P[(int)(randy(1) * 2)] + 1;
  }
  else if( A[P[1]] > A[P[2]] )
  {
    stn = A[P[1]] - A[P[2]];
    col = P[1];
  }
  else if( A[P[1]] < A[P[2]] )
  {
    stn = A[P[2]] - A[P[1]];
    col = P[2];
  }
}

/* Three remaining piles */
static void three()
{
  char *s = "3 Piles";

  if( A[P[1]] == A[P[2]] )
    k = 2;
  else if( A[P[2]] == A[P[3]] )
    k = 1;
  else if( A[P[1]] == A[P[3]] )
    k = 2;
  else
  {    
    three_special();
    return;
  }  
  stn = A[P[k]];
  col = P[k];  
}

/* Three piles special check */
static void three_special()
{
  char *s = "3 Piles Special";
  for( i=1; i<=rr; i++ )
    B[i] = A[P[i]];
  for( i=1; i< rr-1; i++ )
    for( j=i + 1; i<=rr; i++ )
      if( B[i] < B[j] )
      {
	temp = B[i];
	B[i] = B[j];
	B[j] = temp;
	temp = P[i];
	P[i] = P[j];
	P[j] = temp;
      }
  if( B[1] == 3 )
  {    
    random_choice();
    return;
  }
  if( B[3] == 1 && B[2] == 2 )
  {
    stn = B[1] - 3;
    col = P[1];
    return;
  }
  if( B[3] == 1 && B[2] == 3 )
  {
    stn = B[1] - 2;
    col = P[1];
    return;
  }
  if( B[3] == 2 && B[2] == 3 )
  {
    stn = B[1] - 1;
    col = P[1];
    return;
  }
  d3 = B[3] - 1;
  d2 = B[2] - 4;
  dm = B[1] - 5;
  da = abs( d3 - dm - d2 );
  if( d3 == 0 && d2 == 0 && dm == 0 )
  {
    stn = dm - d2 + 1;
    col = P[1];
    return;
  }
  if( dm + d2 == d3 )
  {
    stn = 1;
    col = P[3];
  }
  else if( dm + d2 < d3 && da >= d3 )
  {
    stn = d3;
    col = P[3];
  }
  else if( dm + d2 < d3 && da < d3 )
  {
    stn = da;
    col = P[3];
  }
  else if( dm + d2 > d3 && da <= d2 )
  {
    stn = da;
    col = P[2];
  }
  else if( dm + d2 > d3 && da > d2 && da <= dm )
  {
    stn = da;
    col = P[1];
  }
  else if( dm + d2 > d3 && da > d2 && da > dm )
  {
    stn = da;
    col = P[1];
  }
  else if( dm + d2 > d3 && da == 0 )
  {
    stn = 1;
    col = P[1];
  }
  else if( A[col] - stn == A[P[2]] || A[col] - stn == A[P[3]] )
    stn++;
}

/* Four remaining piles */
static void four()
{
  char *s = "4 Piles";
  am = ch = 0;
  for( i=1; i<=3; i++ )
    F[i] = 0;
  for( i=1; i<= rr; i++ )
  {
    if( A[P[i]] == 1 && F[1] == 0 )
    {
      F[1] = 1;
      ch++;
    }
    if( A[P[i]] == 2 && F[2] == 0 )
    {
      F[2] = 1;
      ch++;
    }
    if( A[P[i]] == 3 && F[3] == 0 )
    {
      F[3] = 1;
      ch++;
    }
    if( am > A[P[i]] )
      continue;
    am  = A[P[i]];
    pm = P[i];    
  }
  if( ch == 2 )
  {
    stn = 1;
    col = pm;
    return;
  }  
  if( ch == 3 )
  {    
    stn = am;
    col = pm;  
    return;
  }  
}

/* Random choice */
static void random_choice()
{
  char *s = "Rand";
  do
  {    
    col = randy(1) * n + 1;
    stn = randy(1) * A[col] + 1;
    if( av <= 5 )
      stn = 1;
  }
  while( stn > A[col] );
}  

/* Declare play */
static void declare()
{
  A[col] -= stn;
}

/* Random number between 0 and n */
static float randy(n)
int n;
{
  return (float)rand() * n / 2147483648.0;
}
